### ISSUE TITLE
Keybase will not confirm reddit.

### ISSUE THREAD

**Issue by Untuned** [keybase/client#10003]
I have reset my keys, and now I am re-verifying my reddit account.  However, the post hasn't been verified.

Proof is here: https://www.reddit.com/r/KeybaseProofs/comments/7l5s92/my_keybase_proof_reddituntunedmc_keybaseuntuned/

Account is here: https://keybase.io/untuned

**Comment by codeyard** [comment]
I have the same issue.

Proof is here:
https://www.reddit.com/r/KeybaseProofs/comments/7l9003/my_keybase_proof_redditcodeyard/

My account: https://keybase.io/raphaelgerber

**Comment by Mrtenz** [comment]
Same issue for me.

**Comment by maxtaco** [comment]
It doesn't work if you're shadow-banned. IT looks like you guys are shadow banned.

**Comment by maxtaco** [comment]
Click on your proof links in an incognito window and you'll see that the body of the post appears deleted.

**Comment by Mrtenz** [comment]
@maxtaco I have never visited the subreddit before, why would I be banned?

**Comment by maxtaco** [comment]
I really have no idea how their system works.  All I know is that if you can't view the post in an incognito window, we can't scrape it from our servers. Can you send me the link of your post?

**Comment by Mrtenz** [comment]
Here is my post: https://www.reddit.com/r/KeybaseProofs/comments/7l8g3i/my_keybase_proof_redditmrtenz_keybasemrten_jcne40/

**Comment by codeyard** [comment]
@Mrtenz It appears to be [removed] as is the case with my post. Is it maybe because I tried approx. 10 times with different posts?

**Comment by Untuned** [comment]
I tried a day later, still shadowbanned.  I don't know why or how it happened :c

**Comment by zapu** [comment]
You should try again, there were some issues with the subreddit but it should be fixed now.

**Comment by klebba** [comment]
Tried this today and it's broken: https://www.reddit.com/r/KeybaseProofs/comments/7ot7n5/my_keybase_proof_redditklebba_keybaseklebba_b/

**Comment by anowlcalledjosh** [comment]
@klebba: The issue is that you're shadowbanned from reddit as a whole, so your posts aren't visible to anyone but yourself. You'll need to contact the reddit admins in order to get the shadowban lifted.

@maxtaco, you can use AutoModerator to automatically approve posts from shadowbanned users in /r/KeybaseProofs if you want to avoid complaints about this. It looks like this check will work ([source](https://www.reddit.com/r/AutoModerator/comments/34s1ep/cannot_auto_approve_shadowbanned_account_posts/cr0np2x/)):

```yaml
author:
    name (regex): ".+"
action: approve
```

You need to explicitly include a check against the author, because by default AutoMod won't approve posts by shadowbanned users:

> AutoModerator will not approve items posted by users that are banned site-wide on reddit unless the approval rule includes a check against author name.

([source](https://www.reddit.com/wiki/automoderator/full-documentation))

Note that if you're not currently using AutoModerator, this will essentially disable reddit's spam filter. You might also want to enforce that posts are formatted as a correct Keybase proof to avoid getting flooded with spam.

**Comment by Plloi** [comment]
Also failed to confirm Reddit: 

https://www.reddit.com/r/KeybaseProofs/comments/83vwb7/my_keybase_proof_redditplloijavex_keybaseplloi/

https://keybase.io/plloi

**Comment by dmccollough1** [comment]
Same issue still here. I can see it when in incognito mode. Post is at
https://www.reddit.com/r/KeybaseProofs/comments/be8rfe/my_keybase_proof_redditdmccollough/
