### ISSUE TITLE
Prompted to rekey for folder but pushing button on UI doesn't fix it

### ISSUE THREAD

**Issue by ProgrammingByPermutation** [keybase/client#12239]
I am prompted to rekey my "private" folder on the UI but clicking the rekey button doesn't seem to be doing anything. I also have a "This computer and possibly others are unable to read some of your folders" dialog which asks me to turn on one of my other devices. Logging into my phone, for example, doesn't appear to be doing anything for the dialog or advancing a solution to the problem.

Not sure what I should do.

my log id: c831805041728871953b901c

**Comment by strib** [comment]
According to our servers, these devices should have access to rekey that folder:

* `android`
* `Home-Desktop`
* `sec-desktop`
* `Laptop`

If you've turned one of these on and it's still not working, can you please send logs from one of those devices?  For a phone, you should be able to send feedback from one of the menus.

**Comment by ProgrammingByPermutation** [comment]
I sent a feedback from my android and the feedback from sec-desktop is 59c7ad6029fa96813a7fe31c.

**Comment by strib** [comment]
Thanks, looking now.  Android: f527850d779f986df4d79c1c.

**Comment by strib** [comment]
This looks like the result of a bug we fixed yesterday.  I didn't think it would affect anyone in practice, but I was wrong!  We're working on getting a new Linux build out that should fix the problem for you, I'll let you know when it's out, and when you install that on `sec-desktop` things should start working again.

**Comment by ProgrammingByPermutation** [comment]
Wonderful! Thank you so much for the quick response and fix! :)

**Comment by strib** [comment]
The new Linux build is finally out.  Please give it a try and let us know if it fixes things for you.

**Comment by ProgrammingByPermutation** [comment]
The new linux build fixed the rekey issue with my private folder "jcyr" but clicking the rekey button for "jcyr,yahya11419" has not resolved.

**Comment by strib** [comment]
It looks like that folder is not keyed for `sec-desktop` unfortunately, it's only keyed for `android`, `Laptop`, and `Home-Desktop`.  If none of those devices are Linux, I guess you'll have to wait for the next release for those platforms unfortunately (maybe in 2 weeks or so).

If one of those devices is macOS, and you like living life on the edge, you can try our latest experimental admin build: https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-2.1.0-20180607144400%2Ba8e869e2ad.dmg, which has the fix but could contain other bugs or weird things.

**Comment by ProgrammingByPermutation** [comment]
The good news is that it went away. The bad news is I don't know why. 

I was mucking with the andriod app trying to trigger a rekey earlier without success and just a few minutes ago I noticed the rekey went away on all devices. 

In any case, I won't be able to verify the windows app fix so we can call this issue closed. 

Thanks for all your help! :)
