### ISSUE TITLE
Error code 218 when accessing KBFS team directory

### ISSUE THREAD

**Issue by JElchison** [keybase/client#13775]
More info on `my log id: 53aa7b1f26261e75acafaf1c`

This is from my wife's Keybase account on her macOS machine.  New Keybase account, fresh Keybase install on macOS.

Screenshot of how listing team directory hangs:

![how listing team directory hangs](https://user-images.githubusercontent.com/1757771/45631968-31d2d300-ba6a-11e8-9cf7-81c327825685.png)

Screenshot of error message on team page:

![error message on team page](https://user-images.githubusercontent.com/1757771/45631983-41521c00-ba6a-11e8-9aa5-810c1cca277c.png)

Thanks for your help!

**Comment by JElchison** [comment]
I'm having similar errors when accessing the same shared team directory, from my own Keybase account on Linux.  Please see `my log id: bf678952b9b34e6d6c64481c`

**Comment by JElchison** [comment]
Because it seems like it might be related, this test team has an owner (me, jelchison) and a writer (my wife, missila).  No admin role.

**Comment by strib** [comment]
@maxtaco related to that other issue?

```
Lookup error=EIO: For team 2fd1a17b09f9c7076cc4b9074d9a3c24, user fd92d4e2140dd8fed6a5547e7e0df719%1: ADMIN role point not found
```

**Comment by keybase-travis** [comment]
Cc @mlsteele

Likely the same issue. Fixed in master.

**Comment by JElchison** [comment]
Thanks all, I will retest using next Linux prerelease and report back.

**Comment by maxtaco** [comment]
I confirmed it's the same issue, sorry about that! We might make a hotfix for it for macOS. Thanks!

**Comment by maxtaco** [comment]
server-side bug, fix going out now, can you restart your app for me?  It should work then. Thanks

**Comment by cuotos** [comment]
I still see the originally raised error with any interactions with one of my teams (viewing users, opening chats, even trying to leave). 

Tried restarting as above, but still an issue. Want it raised as a new issue?

**Comment by maxtaco** [comment]
Send another log and I can look into it in about 2 hours.

**Comment by maxtaco** [comment]
Also, @cuotos that should be fixed, I need to see a log to see what version you are on

**Comment by cuotos** [comment]
log: 4e5d0754a072923541181e1c

**Comment by maxtaco** [comment]
Thank you. We have this fixed in master but we need a hotfix. Maybe we can get to that today, since the damage is greater than we thought. Also @joshblum we might need to revisit our cache bust discussion

**Comment by maxtaco** [comment]
We'll get a hotfix for macOS out today, thanks @cuotos.  The fix is here: https://github.com/keybase/client/pull/13755/files

**Comment by cuotos** [comment]
apologies for my naivety, that will just be a new version from the standard download url?

**Comment by maxtaco** [comment]
We'll push it out via the normal upgrade channel

**Comment by cuotos** [comment]
all seems to be working for me now.

**Comment by maxtaco** [comment]
:+1:

**Comment by JElchison** [comment]
Confirmed working on Linux client `2.7.0-20180920133909+f45dbf2fcf`.  Will report back on macOS client later this weekend.

Thanks for the quick turn-around!
