### ISSUE TITLE
keybase doesn't see my facebook proof

### ISSUE THREAD

**Issue by veriahn** [keybase/client#14537]
I posted my proof on facebook with a public audience settings but after 2 days, I got the message that keybase has given up.

**Comment by Lockcuff** [comment]
I tried this today and have the same failure, but when I try to post I get an error screen from keybase but the proof is still posted.

**Comment by manuelsousa7** [comment]
Tried today and got the same problem as well

**Comment by ptdropper** [comment]
I can add a me too here. My facebook name is robert.smigielski.589 and I can see the posting from keybase. My facebook account uses 2 factor authentication in case that is part of the issue. Each time I try to perform the process from Chrome on Windows 10, Android, or the windows command line I get the same error:  Error 500 something went wrong.

**Comment by manuelsousa7** [comment]
> I can add a me too here. My facebook name is robert.smigielski.589 and I can see the posting from keybase. My facebook account uses 2 factor authentication in case that is part of the issue. Each time I try to perform the process from Chrome on Windows 10, Android, or the windows command line I get the same error: Error 500 something went wrong.

Exactly the same case.

**Comment by Ztocouc** [comment]
I have a similar issue. When I first posted the proof on facebook, I did not notice that it had my default "friends" visibility, so one initial failure was expected. But then I made it public, told keybase I had fixed it and to try again, but still got a failure. Then tried removing my claim and starting again from the beginning, making sure that the "new" proof post was public before I told keybase to check. Still repeatedly failing...

**Comment by maxtaco** [comment]
Our bug, we're working on it today

Thanks for your patience.

**Comment by mlsteele** [comment]
This should be fixed now. Go ahead and try making the proof again.

Any existing proofs that didn't work due to this bug won't automatically recover, but redoing the proof should work now.

**Comment by Ztocouc** [comment]
ok I just deleted the previous post, revoked my claim, and started again from scratch. It works for me now!

**Comment by manuelsousa7** [comment]
It's working now.

**Comment by seclorum** [comment]
Not working for me.  Tried multiple times, revoking, etc.  Still getting 500.

**Comment by ptdropper** [comment]
Just tried again this afternoon and still doesn't work for me. As before I
can see the proof on my Facebook page.

Robert Smigielski

**Comment by numbfall** [comment]
Facebook proof not working. Seeing `Error 500. Something is not right. We will look into it.` on posting prefilled post to facebook. Post is created but keybase is unable to see it.

**Comment by tapuhi** [comment]
I have the same issue, following.

**Comment by Haprog** [comment]
Here's a link to my latest FB proof from yesterday and it still doesn't work: https://www.facebook.com/Haprog/posts/10157487956996030

**Comment by crabovwik** [comment]
Same here

**Comment by davebdb** [comment]
Last night I deleted the proof because I set all my public posts to Facebook and forgot that keybase was on it.  So I deleted and was going to redo the process.  Now the facebook option isn't there anymore.  I see my twitter and github, but Facebook is missing.  Any thoughts?

**Comment by milklineep** [comment]
Facebook is broken, see #14744. I would say this is a duplicate of 14744 but it is not up to me to decide
