### ISSUE TITLE
git-remote-keybase error: (1) keybase isn't running; try `run_keybase`

### ISSUE THREAD

**Issue by joelhelbling** [keybase/client#18986]
With a repo I had pushed to previously, now when I `git push` (or `git pull`), I'm seeing this error: 
```
git-remote-keybase error: (1) keybase isn't running; try `run_keybase`
```
...which of course I attempted, and it restarted the gui, but did not fix this problem.

Running on Linux Mint 19.2.

my log id: 570427be80c80a2eddbc261c

**Comment by strib** [comment]
Thanks for filing a new issue.  Just to cover the bases, is there a chance that you're running the git commands as a different local user (say, `root`) than the local user you're using to run keybase?  I don't see this particular error in the logs you sent as your normal user.

**Comment by joelhelbling** [comment]
No, I'm running the git commands as the same user I'm using to run `run_keybase`.  I'm not using `root` at all here.

**Comment by rkrzr** [comment]
I suddenly started running into the same issue as OP. git used to work fine with this repo and there were no changes from my side AFAIK. My log ID is `9e2989bce4e8dfef40f5fb1c`.

`systemctl --user status keybase keybase.gui kbfs keybase-redirector` reports all services as `active (running)`.

**Comment by maxtaco** [comment]
CC @heronhaye I believe we had a bug in the last release and it should be fixed today in a hotfix.

**Comment by heronhaye** [comment]
Hmm. If you're on 4.3.2 already, do you get any errors when you run `run_keybase` in a terminal?
@joelhelbling @rkrzr

**Comment by rkrzr** [comment]
> Hmm. If you're on 4.3.2 already, do you get any errors when you run run_keybase in a terminal?

No, there are no errors:

```
robert@machine ~/some_git_repo % run_keybase                                                                                                                                                                                      
Shutting down Keybase GUI...
Unmounting /run/user/1000/keybase/kbfs...
Unmounting and shutting down kbfsfuse...
Shutting down keybase service...
Starting via systemd...
run_keybase: Success!
```

The only slightly odd thing that I see in the journald logs are in `kbfs.service`:

```
aug 21 18:20:09 machine systemd[1960]: Starting Keybase Filesystem service...
aug 21 18:20:09 machine sh[1012]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab
aug 21 18:20:10 machine systemd[1960]: Started Keybase Filesystem service.
```

The "entry not found" seems weird, since there is such an entry:

```
robert@machine ~/some_git_repo % cat /etc/mtab | grep "/run/user/1000/keybase/kbfs"                                                                                                                                                 
/dev/fuse /run/user/1000/keybase/kbfs fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
```

I don't know whether this is related to this problem though.

**Comment by strib** [comment]
Strange.  In @rkrzr's git logs, there's no activity since 8/16, but in the keybase service logs, there's activity up until 8/21.  So it seems like either the logging is being routed to an unusual location somehow, or maybe the ownership of the git log changed, or the git command is somehow being run under a different user, with logs stored in a different location.

@rkrzr can you check the ownership and mod time of your `~/.cache/keybase/keybase.git.log` file?  Check it both before and after attempting a git command please.  Also, just to be safe, check for similar logs in other local user's home directories (e.g. `root`).  Seems unlikely, but worth checking out to eliminate as a possibility.

In your old git logs, it's looking for the service to have a socket open at `/run/user/1000/keybase/keybased.sock`.  Does that file exist now?  (Looking at your service logs, I think it should.)  I wonder if another possibility is that somehow the `$XDG_RUNTIME_DIR` variable isn't set correctly for your git process, so it's looking for the socket in the wrong location, and thus thinks keybase isn't running.

> The only slightly odd thing that I see in the journald logs are in kbfs.service:
> 
> aug 21 18:20:09 machine systemd[1960]: Starting Keybase Filesystem service...
> aug 21 18:20:09 machine sh[1012]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab
> aug 21 18:20:10 machine systemd[1960]: Started Keybase Filesystem service.

This is fine and normal, this happens before the mount occurs and is just a fallback in case somehow a mount is leftover from a previous run.

**Comment by rkrzr** [comment]
I'm on a different machine now (also `Ubuntu 18.04.3 LTS`, `Client:  4.2.1-20190718132443+117e8ce562`), which also has the same git repo and also used to work, and I can reproduce the issue here.
Upgrading to `Client:  4.3.2-20190820191250+4c5189b6e2` did not fix it.

> @rkrzr can you check the ownership and mod time of your ~/.cache/keybase/keybase.git.log file? 

On this machine this is

```
-rw------- 1 rob rob 106M jun 10 09:42 keybase.git.log
```

It stays the same both before and after running `git pull`, so this file does not change.

>  Also, just to be safe, check for similar logs in other local user's home directories (e.g. root)

There are no other users with this file.

> In your old git logs, it's looking for the service to have a socket open at /run/user/1000/keybase/keybased.sock. Does that file exist now?

Yes that file exists:

```
srwxr-xr-x 1 rob rob 0 aug 21 22:09 /run/user/1000/keybase/keybased.sock
```

>  I wonder if another possibility is that somehow the $XDG_RUNTIME_DIR variable isn't set correctly for your git process

It's set to `XDG_RUNTIME_DIR=/run/user/1000` in my shell session, which seems correct.

Is there something else I can try?
(New log id: `680d945545f42da90348bf1c`)

**Comment by strib** [comment]
@rkrzr Thanks for the info!  If you're willing to go down the rabbit hole with me, you can try this:

```sh
strace -f git-remote-keybase 2>&1 | tee /tmp/git_trace.out
```

Which should fail with the same error.

Then look through `/tmp/git_trace.out` for files ending in ".sock" and see what socket it's trying and failing to connect to.

**Comment by rkrzr** [comment]
Sure, let's get to the bottom of this.

> Then look through /tmp/git_trace.out for files ending in ".sock" and see what socket it's trying and failing to connect to.

It doesn't seem to fail to connect to a socket. 

```
[pid 31318] connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1000/keybase/keybased.sock"}, 39) = 0
```

This socket exists.

The actual error seems to be:

```
[pid 31318] write(3, "git-remote-keybase error: (1) no"..., 55git-remote-keybase error: (1) no remote repo specified
```

So it seems that `git-remote-keybase` is called with the wrong arguments perhaps?

How does `git pull` interact with `git-remote-keybase` btw? Is that a git hook somewhere?

This works btw:

```
robert@machine ~/some_git_repo % git-remote-keybase origin keybase://private/username/some_git_repo                                                                                                                       
Initializing Keybase... done.
```

Plot twist: If I run git commands *with strace* they *do work*!
This works:

```
strace -f git clone keybase://private/username/some_git_repo
```

This doesn't:

```
git clone keybase://private/username/some_git_repo
```

I'm at a loss here.

(I'm happy to send you the output of strace, if that helps)

**Comment by strib** [comment]
So `git` executes the `git-remote-keybase` command under the covers, and it looks like what's happening is that it doesn't pass along the `$XDG` variables in the execution environment for some reason.  If so, that'd be some local config or git-specific issue.  Hmm.  Unfortunately I'm not working today but that's what I'd look into next...

**Comment by strib** [comment]
I wonder if somehow your `$XDG` variables are set manually in your shell environment, but they're not exported so that subprocesses don't inherit the settings?

**Comment by rkrzr** [comment]
> I wonder if somehow your $XDG variables are set manually in your shell environment, but they're not exported so that subprocesses don't inherit the settings?

No, I'm not setting $XDG variables manually, but the problem is indeed with my shell:
If I'm running `git pull` in `zsh` (my regular shell) it does not work and I get the error in the title. But if I run `git pull` in `bash` then it does work.

`zsh` used to work just fine, and I don't know yet what changed (there were no changes to my `.zshrc` AFAIK). If I delete my `.zshrc` the problem is fixed.

**Found it**:

I use a zsh plugin called `github`, which causes this problem.
If I remove this plugin from the `plugins=(...)` line and then `exec zsh` and `git pull` then the problem is solved.

I have not investigated further *why* this plugin causes this to break (likely because it messes with the $XDG env vars, like you said), but I'm happy that it's working again. Thanks again for your help!

**Comment by rkrzr** [comment]
Ha, yeah, it gets better:

The `github` plugin is part of `oh-my-zsh` and does [this](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/github/github.plugin.zsh#L3):

```bash
if (( $+commands[hub] )); then
  alias git=hub
fi
```

So I wasn't actually running the `git` binary, but the `hub` binary, which is a [thing from GH](https://github.com/github/hub).
And I actually do remember upgrading `hub` recently. I therefore assume that `hub` used to pass these env vars through correctly, but no longer does so. So I should probably go and open an issue with them now (also: stop using zsh plugins that I never use).

**Comment by strib** [comment]
Great detective work, thanks @rkrzr!  @joelhelbling do you also use `oh-my-zsh`?

**Comment by joelhelbling** [comment]
No, I'm using bash.  I'm running on Mint 19.  And I _also_ have `hub` installed (via snap).  When I `snap remove hub`, and restart my shell, git (with a keybase repo) works again!  hooray.  I think I did install `hub` recently, so it could be as simple as that.

On reinstalling, I am reminded that
```
error: This revision of snap "hub" was published using classic confinement and thus may perform
       arbitrary system changes outside of the security sandbox that snaps are usually confined to,
       which may put your system at risk.

       If you understand and want to proceed repeat the command including --classic.
```
So now I remember that I had to `snap install hub --classic`.  Meh.  I don't use `hub` much, so I'll dump it in favor of keybase encrypted repos.

**Comment by strib** [comment]
Great, glad it's working again!

**Comment by teh0xqb** [comment]
I ran into this. Ended up figuring out while having read this discussion halfway.

Some other temporary workarounds, if you'd like to keep using hub for other projects:
### unalias git per session
```
unalias git
```
alternatively, you can run the command un-aliased per occurrence. Example:
```
\git push --all
```

**Comment by hootieben** [comment]
Just as another followup, the problem appears to be with snap. Running the snap binary produces the above errors. Downloading the binary artifact of hub and running that natively produces no errors.
