### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by astronouth7303** [keybase/client#19875]
Cannot access kbfs, "Transport endpoint is not connected"

my log id: 56fefc8c2fa1504ae7cd5e1c

I reboot regularly. KBFS is inaccessible to me.

Running Debiant testing, kept up-to-date daily.

**Comment by strib** [comment]
Sorry about the bad experience. It looks like KBFS is continuously crashing when loading the history of updates for a certain team (I'll DM you the team name on Keybase).  I think this is due to an old bug that we've fixed -- it's been happening to you since June.  Clearly it needs another fix to avoid the crashing, so I'll work on that.

But in the meantime, until we get a new release out, you might (?) be able to fix it by going into this team's folder on a mobile device and uploading like 10-20 files to it (just any files, as long as you give them all different names).  But I'm not 100% sure that mobile won't crash too.  If it does, I can make a special Linux build for you with the fix.

**Comment by astronouth7303** [comment]
So I uploaded 12 files via mobile.

Desktop spun for a while.

And then it crashed again.

Mobile does not seem to be crashing.

**Comment by SOF3** [comment]
I just updated keybase via apt, and I am unable to use kbfs.
Doing `stat` or `df` on `/keybase` emits the error "Transport endpoint is not connected".

I have not tried rebooting my computer yet.
Tried running `run_keybase` to restart keybase, twice.

c857a0a0bfc0f36bd256251c

**Comment by SOF3** [comment]
Rebooting my Ubuntu resolved the issue. Nevertheless it is still strange that merely restarting keybase didn't work.

**Comment by totedati** [comment]
Well, i updated keybase for many times till now, kubuntu bionic beaver 18.04, i have months of uptime with no crash but i still get this 

> Transport endpoint is not connected

error from time to time ... Last time i see that i can reproduce consistently this error when i logout/login from console, look like after login if kbfs service was already active is not succesfully restarted/refreshed/reconected to keybase servers and the /keybase mount point is now a strange singularity in / 
But on my case `run_keybase` command or the simple `systemctl --user restart kbfs.service` command can solve this problem no need till now for a real machine restart

**Comment by erAck** [comment]
If running `run_keybase` again doesn't solve it and after
```
systemctl --user restart kbfs.service
```
still no luck then do `run_keybase -k` to kill Keybase and then issuing the
```
sudo fusermount -u /keybase
```
command should solve it, see https://github.com/keybase/client/issues/20331
