### ISSUE TITLE
Certificate for api-0.core.keybaseapi.com expired

### ISSUE THREAD

**Issue by gonzalob** [keybase/client#26088]
<img width="965" alt="Screenshot 2023-12-31 at 13 56 56" src="https://github.com/keybase/client/assets/1843816/12c8ded3-d355-48f7-a49b-228b02d1f564">

**Comment by aikooo7** [comment]
Happens to me too

**Comment by socketbox** [comment]
Apparently happened last year as well:
![image](https://github.com/keybase/client/assets/1593835/bbbaf7ef-d725-4a32-81a7-6d7331869977)

**Comment by aikooo7** [comment]
> Apparently happened last year as well: ![image](https://private-user-images.githubusercontent.com/1593835/293517820-bbbaf7ef-d725-4a32-81a7-6d7331869977.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDY4OTQsIm5iZiI6MTcwNDA0NjU5NCwicGF0aCI6Ii8xNTkzODM1LzI5MzUxNzgyMC1iYmJhZjdlZi1kNzI1LTRhMzItODFhNy02ZDczMzE4Njk5NzcuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE4MTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkM2Q3M2FkMjc1MmU2YTc5ZDhjNWY0YzcwMDZiMWFmNDc4ZGVlYzI0MTkzYmRiZjE5MWEwYzlmYTJlYzExNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Au_ERcbP9AGhLM-SR0wfn5xHR_dWlbrgZZOW3lFxJs4)

My first searches gone into older GitHub issues into you found this one

**Comment by oscoDOTblog** [comment]
bump, same issue

**Comment by jlopp** [comment]
Oof; desktop client appears completely broken just because of an expired certificate?

**Comment by samira** [comment]
Ironically can't even send a bug report from within the app.

**Comment by chrisnojima** [comment]
we're aware of the issue and are working on it

**Comment by aikooo7** [comment]
> Oof; desktop client appears completely broken just because of an expired certificate?

Yes, it uses the API for part of the UI (assumption)

**Comment by aikooo7** [comment]
> Ironically can't even send a bug report from within the app.

The bug report sends it to the API so it can't actually send it xd

**Comment by gene1wood** [comment]
Fixed in fbebbc9f1ba29e21ae6d3ee2edc21a7703d0019f

Note on the [Android app release](https://play.google.com/store/apps/details?id=io.keybase.ossifrage) just now

> Fix for expired certificate issues which caused connection issues
> To fix desktop apps please redownload the app from keybase.io

@mmaxim Will there be any further communication to keybase users to know that they have to redownload the app? Maybe a blog post?

**Comment by aymanoid** [comment]
> Fixed in [fbebbc9](https://github.com/keybase/client/commit/fbebbc9f1ba29e21ae6d3ee2edc21a7703d0019f)
> 
> Note on the [Android app release](https://play.google.com/store/apps/details?id=io.keybase.ossifrage) just now
> 
> > Fix for expired certificate issues which caused connection issues
> > To fix desktop apps please redownload the app from keybase.io
> 
> @mmaxim Will there be any further communication to keybase users to know that they have to redownload the app? Maybe a blog post?

thanks, but `kbp.keybaseapi.com` seems to still be missing certs

**Comment by aymanoid** [comment]
Update: `kbp.keybaseapi.com` appears to be working now, I think this issue can be closed

**Comment by gonzalob** [comment]
MacOS version needs to be re-downloaded manually for this fix to kick in, since the updater itself doesn't work.

**Comment by waldner** [comment]
I'm still getting this when trying to login with paper key:

```
2024-01-01T14:44:45.013783+01:00 ▶ [ERRO keybase main.go:87] 002 API network error: doRetry failed, attempts: 3, timeout 13.5s, last err: Get https://api-0.core.keybaseapi.com/_/api/1.0/user/lookup.json?fields=basics&load_deleted_v2=1&multi=1&username=waldner: x509: issuer name does not match subject from issuing certificate (code 1601)
```

is that something to fix on my side?

```
keybase 6.2.4-20240101011938.ae7e4a1c15
```

**Comment by terminalfool** [comment]
ios version still broken. Manually updating worsens the problem.

**Comment by aymanoid** [comment]
> ios version still broken. Manually updating worsens the problem.

Apple hasn't approved the new fixed version on the App Store yet, the process can take some time, so just be patient
