### ISSUE TITLE
Remove all the Spam issues innodating this repo

### ISSUE THREAD

**Issue by compuguy** [keybase/client#26657]
Somone with repo privileges needs to delete/report all these spam issues and post from the past month or so.

This is a incomplete list of all the spammer accounts:
- https://github.com/Nylaloc
- https://github.com/MiaLudovic
- https://github.com/trudycharles
- https://github.com/Deason2
- https://github.com/Angelamisan
- https://github.com/NancyGochnauer
- https://github.com/TristanOrson
- https://github.com/RolandAlexandersummers
- https://github.com/Allisonlawrence
- https://github.com/MrsFeliciaBarrett
- https://github.com/Lianchii
- https://github.com/mccarthyfrazier
- https://github.com/Juliettemarie0
- https://github.com/emilyfaye3
- https://github.com/jamesbelich
- https://github.com/bettysabatine

All of these accounts are inauthentic and have recently been created in the past several days just to spam crypto scams and the like.

![image](https://github.com/keybase/client/assets/864349/424b2f11-e6a9-4784-8407-4d8d1252ed12)

**Comment by compuguy** [comment]
Seriously @github-staff can you spend a few minutes pruning out all these spam issues/tickets!

**Comment by Espionage724** [comment]
I'll volunteer to clean-up some spam in this repo!

**Comment by compuguy** [comment]
> Looks like no one cares. My trust chain broke somehow and now my account is unusable :'(

Honestly it's one of the people who have project access like @joshblum or @michalz-zoom that can easily report all this spam. Or a user who regularly contributes to this repo. Otherwise it's quite laborious to report all this manually...

**Comment by compuguy** [comment]
Looks like this has been resolved. I'm closing the issue.

**Comment by compuguy** [comment]
Yeah, we're still getting issue spam:
https://github.com/keybase/client/issues/26809

**Comment by Espionage724** [comment]
I'm still somewhat interested in helping to clean-up spam!

**Comment by kg4zow** [comment]
Still happening.

And the "Report an issue" selection which is *supposed to be* on the "..." menu at the top right of the spam message, isn't there.

**Comment by compuguy** [comment]
That only shows up if you have certain privileges to the project and/or repo, or one has the contributor badge.Sent from Re:WorkFrom: John Simpson ***@***.***>Sent: Tuesday, April 30, 2024 5:16 PMTo: keybase/clientCc: Alex Hall; State changeSubject: Re: [keybase/client] Remove all the Spam issues innodating this repo (Issue #26657)
Still happening.
And the "Report an issue" selection which is supposed to be on the "..." menu at the top right of the spam message, isn't there.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/keybase/client/issues/26657#issuecomment-2087350285",
"url": "https://github.com/keybase/client/issues/26657#issuecomment-2087350285",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by FergusonMiriam** [comment]
A few months ago, I was approached by an individual who claimed to be a successful cryptocurrency trader with a foolproof investment opportunity. They promised high returns in a short period and assured me that my investment was safe and secure. Filled with excitement and the prospect of making quick profits, I decided to invest a significant amount of money in the scheme. The initial weeks seemed promising as I saw small returns on my investment, which further fueled my belief in the operation's legitimacy. However, as time passed, the individual became increasingly difficult to reach, and my requests to withdraw my profits were ignored. It soon became clear that I had fallen victim to a cryptocurrency investment scam. I had lost a substantial sum of money, and the promises of high returns were nothing but a facade to lure unsuspecting investors.   However, I refused to give up hope and began searching for solutions online. That's when I came across Trust Geeks Hack Expert  specializes in recovering stolen cryptocurrency. I reached out to them and explained my situation, and they immediately sprang into action. Through their expertise, determination, and relentless effort, they were able to track down my lost Bitcoin and recover it for me. I was overjoyed and relieved beyond words when I received the news that my funds had been successfully retrieved. If you find yourself in a similar situation look for assistance from Trust Geeks Hack Expert. I urge everyone to exercise caution when approached with investment opportunities that seem too good to be true, especially in the realm of cryptocurrency. 

Contact Service 
Email::  trustgeekshackexpert[Dot]fastservice[At]come
 Website. https://trustgeekshackexpert.com/
 Telegram ID : Trustgeekshackexpert

**Comment by CarlDenis001** [comment]
First and foremost,
I would want to thank Lord Royal Hacker for their tireless efforts
in aiding me in getting my misplaced cryptocurrency worth approximately $56,800
My objective while investing in an online business was to earn a weekly profit of 20%,
but it turned out to be a hoax. I assumed that i was done for, 
but I soon found out Lord Royal Hacker had actually assisted others
in getting back their crypocurrency after reading a review about them.
Contact them right now to receive the greatest rehabilitation assistance.

website : https://lordroyalhacker.com
E-mail address: Lordroyalhacker@aol.com
WhatsApp number: +1-716-216-5226
Lordroyalhacker on Telegram

**Comment by Espionage724** [comment]
What the heck, add me so I can clean spam up like the above, or figure it out as I don't get this spam from other repos and I'd consider this vaporware if Keybase didn't work decently for me in the past.

**Comment by Gallium70** [comment]
They are spamming now again. Honestly it's hard to clean them up once and for all, since it costs almost nothing to sign up an account and spam everywhere. 

![image](https://github.com/keybase/client/assets/52118815/eea0043b-a321-454d-8111-14c57c2af5f8)
