### ISSUE TITLE
ls: cannot open directory '/keybase/private/benkietzman': Input/output error

### ISSUE THREAD

**Issue by benkietzman** [keybase/client#3143]
I have reset my keys and started from scratch probably five times.  My first attempt was trying to copy data to keybase and would occasionally get copy errors.  I had three computer devices.  One of them got out of sync with the others so I decided to manually remove the data from all the devices.  Then I kept hitting an issue where it could not remove a particular JPG file.  At that point I decided to try revoking and re-adding devices.  That did not fix anything.  So then I decided to do my first reset of keys and start from scratch.  Going forward from there I kept getting the issue I am now filing where I get the Input/output error.  This error occurs on all the keybase private and public folders.  Over time I have reset my keys and started from scratch multiple times and have also revoked and re-added devices multiple time.  The error remains the same.

Looking at the keybase.kbfs.log I see the following error:

[DEBU FUSE serve.go:845] 232 -> [ID=0x46] Open error=EIO: /keybase/private/benkietzman was last written by an unknown device claiming to belong to user benkietzman.  The device has possibly been revoked by the user.  Use `keybase log send` to file an issue with the Keybase admins.

my log id: 1f65526758669e087875fd1c

**Comment by strib** [comment]
@benkietzman: we don't currently support automatically fixing up your folders when you reset your keys.  (We are actively working on it though!)  We can manually nuke your single-writer folders if you want to get back to using KBFS, but the data will be lost.

If you want that, we need to have a public, signed request from you. Please run the following command on one of your devices, and substitute the current date and time as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folders /keybase/private/benkietzman and /keybase/public/benkietzman because I reset my Keybase account."
```

and post the output here. Thanks!

**Comment by benkietzman** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsLLK1qK FYXsv0yKtUbA7ua yz9UsX7cUNJS9wk cTEB6Gs6TJ7BMlP BBaeuKuiFUFCSE5 phgKOYEFYP87R5y EzFIUsteyM4M2eD oCIzRMmOljnpAjo yhet0m4Q8x3CYCY 0K0aMzuRvkP2Ygc uDtbjaAeb73cyhL f9GczxHMpriCLGd ozwXx50l8XZ4pgV 0kmrjNylvwNI9QZ gqIOVnehkoGb9fz yM6OFRKQJG5IwRT U9qN6jN0RDxFNpN mwail5kYfvu2JYa MrFQdKW4ZFrVPh0 5NKP0Ss2D4GVqcE pPbRCak2p6z04Z8 3HZ7a2wAtbtOQyH L7HNtIsYzb4hBS1 v9mNX8tDoUkqsAb 8aH4JOcI1cPYgJE edNuT4FsNF3GP9U wEgOzbRV3UfOSkU 9O4R3JU2DmDlxje 45bu4trMUtAw150 5oMmzK92DrAqrjG 5cwePITw. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Ok, done!  Check it out and please close this if your folders seem restored.  Thanks!

**Comment by benkietzman** [comment]
Thank you!  That appears to have done the trick for /keybase/private/benkietzman and /keybase/public/benkietzman.  However, it looks like I am still seeing that issue for /keybase/private/benkietzman,jeffbristow.  Would that be related to the same underlying issue?

[DEBU FUSE serve.go:845] 47d -> [ID=0x8d] Open error=EIO: /keybase/private/benkietzman,jeffbristow was last written by an unknown device claiming to belong to user benkietzman.  The device has possibly been revoked by the user.  Use `keybase log send` to file an issue with the Keybase admins.

Sorry for the hassle on this.

**Comment by strib** [comment]
Dang, sorry @benkietzman!  I should have thought to ask you if you had been the most-recent writer on any other folders.  If you're ok resetting that folder too (and losing all of its data), please post another signed message like the one above, including that folder name.

If you have data in there you'd rather not lose (which is a perfectly reasonable position to take), we can work with you on a hacky workaround, or you can wait a bit for us to finish our current project for making these old pre-reset folders accessible under new folder names.

**Comment by jeffbristow** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

The data we have in there is not important, you can rest it as that sounds like the best fix.

Thanks!

keybase.io/jeffbristow

-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.53
Comment: https://keybase.io/crypto

wsBcBAABCgAGBQJXaT/9AAoJEIJRYW2epWdCTzAH/RmodJtE7CCQMTj4/iHuJhoi
6i4mqWMaVBwOdgkV2dztE3rfyKmudocgeROSDiCosblAhxeF9TG2d+fdfoTAaIww
TrB9+a8VSU0O8ytOmT2mvldk8B6bwewDTY5uFa+IXwsUcW5uy26DtTHndTJIisdf
vGZ3OmnJjkIpeq5WKzLqv0XkWzwV7zWjELKAWhJNAqY0ZzDr/98nESHfl8Dq9d9H
IyeLrX7mwLHl629JlMFzDrBLqTpumTzHDlLC7ia+Fp9vSJrcBXfnjc/Yi6dx62e0
oZ1OjMvdVvj/G9KlZbgxOgYheKhlIvj2sg6RqJS0u7hdPsSxuPIn3DtPMHaoioQ=
=mADY
-----END PGP SIGNATURE-----

**Comment by benkietzman** [comment]
Losing the data is fine.  Thank you for working with me on this.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsLLK1qK FYXsv0yKtUbA7ua yz9UsX7cUNJS9wk cTEB6Gs6TIVsniM cwRsZDZRMIcGxwR DO26W9jAzbU6QEl nSquvo5iyQzXwxi A4TrYe8VIGLkViK 6VORD8CQhe77juP PaEbmdV86XjUd6W BTFOe67y5DBQrrJ ncHtbe4q0n4ZRN4 XchpTSCAXVJpPb6 SbeHTNylvwNI9QZ gqIOVnehkoGb9fz yM6OFRKQJG5IwRT U9qN6jN0RDxFNpN mwail5kYfvu2JYa MrFQhb1ybHXVCYN fRbqShu6WqePvmS BKFSOHFziHe2bCm eevji7MmpKIzGzN ZDbVBHeUDdUjcnE pr7p6cR1WPFQaPA jdzY8a4OFitlB6C KvXKakxwWE8AlVT 9vASYjxvLPCmk3P CCTdygQWGE0w7oX aYffzMyYwCCO. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Ok @benkietzman @jeffbristow, should be reset now.  Let me know if you have other issues, and sorry for the inconvenience!

**Comment by borrrden** [comment]
For what it's worth I think I've run into the same thing.  I ran `keybase paperkey` thinking that I could view my current key, and it suddenly informed me that it was generating a new one and if I wanted to revoke the old one.  I felt a bit scared to I killed the process before I could do any more damage but I guess the damage has already been done?

I still have my old paper key, and I entered it using `keybase rekey paper` but still the error persists.  Should I send the same message?

**Comment by arneheggestad** [comment]
I'm having the same issue after the most recent update. All of my KBFS folders appear to be empty in finder, and `ls` on the command line gives me `ls: .: Input/output error`.

I'm on OS X Yosemite, in case that matters.

Keybase GUI Version: 1.0.16-20160621190121+4d16a4b.

**Comment by cjb** [comment]
@arneheggestad Please can you run `keybase log send` on the machine that isn't working? Thanks!

**Comment by arneheggestad** [comment]
@cjb Done. Log ID is `7dc61abf346cd3ee01764c1c`. Thanks for looking into this!

**Comment by cjb** [comment]
@arneheggestad Thanks! Did you revoke any devices recently? Please could you try: `keybase logout && keybase login`?

**Comment by arneheggestad** [comment]
@cjb I haven't revoked any devices lately, no. I logged out and back in and am still having the same issue.

**Comment by cjb** [comment]
@arneheggestad Thanks!  This looks like it's affecting several users, we're working on it now.

@borrrden Please could you run `keybase log send`?

**Comment by arneheggestad** [comment]
@cjb Right on. I've got the data backed up elsewhere, so it's not the end of the world if the folders' contents are lost. Thanks again!

**Comment by borrrden** [comment]
Done -> efdb38c29e76da1054c65c1c

**Comment by benkietzman** [comment]
@strib , thank you for your help.  It's no inconvenience.  So a quick update.  Yesterday, I had three computers registered as devices (office4, server4, and slim4).  Two of them (server4 and slim4) worked great and one of them (office4) kept failing with the following error when attempting to do a listing of /keybase/private/benkietzman:

ls: cannot open directory '.': Input/output error

Now this morning I noticed that my server4 device is doing the same thing as office4 even though it looked good yesterday.  So I decided to add a new device called work4 on a different computer just to see.  That new device is also showing the error message.  Looks like something happened from yesterday to today.

How would you like to proceed?  Thank you again for all your assistance on this.

**Comment by cjb** [comment]
@benkietzman Hi!  Strib's on the west coast so he'll be asleep for a while -- but I can tell you that we're working on a KBFS outage that's unrelated to your reset issue.  So let's retest again once that's resolved.  Thanks!

**Comment by borrrden** [comment]
@cjb it looks suspiciously like a security token used during the HTTP calls got changed, but I haven't looked terribly into it.  I started to suspect something as well when a working directory became non working on remount.  The fact that things are streamed on demand was a clue to that.  Ping me when I should try again.  I'm looking forward to it like a kid on Christmas 💃

**Comment by cjb** [comment]
@benkietzman @borrrden @arneheggestad I think our server-side's fixed now, please could you retry your KBFS operations?

**Comment by borrrden** [comment]
beautiful!  Things are working for me

**Comment by benkietzman** [comment]
@cjb that worked!  Nice going.

**Comment by arneheggestad** [comment]
@cjb Working like a charm. I still have the notification dot (saying that my personal private folder is new) up on the Keybase menu bar icon but honestly I rarely use the Keybase UI client.

Thanks again!

**Comment by cjb** [comment]
Great, thanks everyone!  Our apologies for the outage today, we'll work on avoiding a repeat.

**Comment by benkietzman** [comment]
Shall I close this issue?

**Comment by cjb** [comment]
Sounds good, I'll close it.
