### ISSUE TITLE
can't select pgp key

### ISSUE THREAD

**Issue by rejozenger** [keybase/client#5872]
When running "keybase pgp select" I run into the following error:
```
2017-02-14T23:34:48.762280 ▶ [DEBU keybase log.go:30] 0a8 | running Gpg: /usr/local/bin/gpg2 --no-tty --armor --export-secret-key 1fbf7b37653768b12532a4cb0994094621dbefd4
2017-02-14T23:34:48.762585 ▶ [DEBU keybase log.go:30] 0a9 | setting GPG_TTY=/dev/ttys001
2017-02-14T23:34:48.769913 ▶ [WARN keybase log.go:34] 0aa Bad subkey: openpgp: invalid data: subkey signature invalid: openpgp: invalid signature: RSA verification failure
2017-02-14T23:34:48.771662 ▶ [DEBU keybase log.go:30] 0ab GPG version:
gpg (GnuPG) 2.0.30
libgcrypt 1.7.6
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA, RSA, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
2017-02-14T23:34:48.773005 ▶ [DEBU keybase log.go:30] 0ac | running Gpg: /usr/local/bin/gpg2 --no-tty --armor --export 1fbf7b37653768b12532a4cb0994094621dbefd4
2017-02-14T23:34:48.773422 ▶ [DEBU keybase log.go:30] 0ad | setting GPG_TTY=/dev/ttys001
2017-02-14T23:34:48.854519 ▶ [DEBU keybase log.go:30] 0ae SecretUI:GetPassphrase, sessionID = 0
2017-02-14T23:35:04.589684 ▶ [DEBU keybase log.go:30] 0af SecretUI:GetPassphrase, sessionID = 0
```

At this point, I have a dialog asking for the passphrase, but that doesn't work: it tells me I have not provided the valid passphrase.

Maybe relevant: the private key is on a Gemalto smartcard.

Maybe relevant:
```
pub  4096R/0x0994094621DBEFD4  created: 2009-06-26  expires: 2018-02-14  usage: SC
                               trust: ultimate      validity: ultimate
sub  4096R/0xE9821730F3198A94  created: 2009-06-26  expires: never       usage: E
sub  4096R/0x89B6FE7DB6633197  created: 2014-03-22  expires: 2018-02-14  usage: S
```

**Comment by johanbove** [comment]
Thanks for reporting your problem @rejozenger . I would suggest to also add an official keybase log in this ticket. To submit your keybase logs, run in a command prompt: `keybase log send` and copy the given ID of the log here. This should help debug your issue.

**Comment by rejozenger** [comment]
Done. The ID is "82360add8a227e7c6a5dfe1c".

**Comment by maxtaco** [comment]
This is likely the same issue as https://github.com/keybase/keybase-issues/issues/2575

we hope to look into it shortly

**Comment by zapu** [comment]
Could you try that again? A week or two we introduced a couple of fixes to passphrases - we were asking for  passphrases for non-passworded keys, and also it was worded as if keybase password was required. Thank you

**Comment by rejozenger** [comment]
I have reinstalled the application and seem to be running version "1.0.20-20170309192151+e30557a". The same issue occurs.

Side note: my private key is not non-passworded and the messaging suggested (and still does) that it needs the password to my private key.

**Comment by zapu** [comment]
Thanks for doing that, sad to hear it's still not working. Can you send the log again?

 Is any of the keys passworded or none of the keys is?

**Comment by rejozenger** [comment]
Yes. This is the ID: 04ffcf11bf2ca83fd8f4131c. There is only a single private key on the key ring and that is password protected.

```
rejo@ix3:~$ gpg --list-secret-keys
/Users/rejo/.gnupg/secring.gpg
------------------------------
sec>  4096R/0x0994094621DBEFD4 2009-06-26 [expires: 2018-02-02]
      Card serial no. = 0005 0000[xxxx]
uid                            Rejo Zenger <rejo@zenger.nl>
uid                            Rejo Zenger (Bits of Freedom) <rejo.zenger@bof.nl>
uid                            Rejo Zenger (IFCAT) <rejo@ifcat.org>
uid                            Rejo Zenger (Freedom Inc) <rejo.zenger@freedominc.nl>
ssb>  4096R/0xE9821730F3198A94 2009-06-26
ssb   4096R/0x89B6FE7DB6633197 2014-03-22
```

**Comment by zapu** [comment]
Thank you for getting back to me! Could you clarify, that the primary key (and subkeys) has **no** passphrase or it (or all of them) **does have** a passphrase? Unless I am reading it wrong, the two comments contradict one another. Thanks!

**Comment by zapu** [comment]
oh, oops, or rather what you meant was that one of the subkeys is password protected (but not primary) ?

**Comment by rejozenger** [comment]
What I meant to say is that I have a smartcard with my private key on it and that this key is password protected. I have no special configuration with regard to subkeys and I would say that "the primary key (and subkeys)" are protected by a single passphrase. Does that clarify?

**Comment by zapu** [comment]
Oh, that makes sense. I will try to reproduce this setup and see if what exactly is broken. Thanks again for helping with this bug!
