### ISSUE TITLE
keybase rekey warning, cannot rekey

### ISSUE THREAD

**Issue by soulware** [keybase/client#8776]
This issue appears to be reoccurring on a new device - 
keybase/client#7629

I installed keybase on a new laptop and the app is prompting me to turn on another device or enter a paper key.
Neither of which appear to resolve the issue.

I get this from the command line - 
```
keybase rekey status
TLFs need rekeying:
private/soulware

Devices that can rekey:
backup	<redacted>
desktop	macbook_q
mobile	iphone
``` 

Running `keybase rekey paper` has no effect. I can enter the paper key but the issue persists.

Assuming logs will help so here you go - 

```
keybase log send

------------
Success! Your log ID is:

  c1439726bf1dc5c596b4921c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20c1439726bf1dc5c596b4921c

Thanks!
------------
```

**Comment by maxtaco** [comment]
cc: @songgao / @jzila / @strib

**Comment by strib** [comment]
@maxtaco @oconnor663 : the TLF showing up for a rekey is an old folder that's since been reset (#7629).  We need to wipe it from the kbfstld db.  The TLF ID is `53c15aff9406acee0c8aa0fdbb1bf916`.

**Comment by strib** [comment]
Oh wait, I forgot that I know how to do this.  I'll put up a PR in a sec.

**Comment by strib** [comment]
@soulware This will be fixed on the next server deploy.  Sorry about that!

**Comment by diego898** [comment]
Hello - I am not sure if this is realted to my problem. I got a new laptop so I decided to revoke everything and start over. I installed keybase on my new computer, and verified my identities. Now in the GUI when I go to chat, it tells me I need to rekey. I press the rekey button but nothing happens. 

In the command line when I type in `keybase rekey status` I get: `No TLFs need rekeying.`

**Comment by diego898** [comment]
Now I see the following: 

<img width="702" alt="screen shot 2017-10-06 at 3 43 00 pm" src="https://user-images.githubusercontent.com/742407/31297815-1db0943e-aaad-11e7-8cec-4a186a648763.png">

**Comment by copyhacker** [comment]
Same symptom as @soulware here. Log ID is `7513bee88be799b57a237c1c`

**Comment by strib** [comment]
@copyhacker: yeah, you've had reset folders in the past too.  Should be fixed on our next server deploy.

**Comment by diego898** [comment]
@strib can you comment on whether or not my issue is related here?

**Comment by strib** [comment]
@diego898: your issue seems unrelated and probably warrants a new github issue (and a `keybase log send`, if you're willing).  It might be known already, I know some other folks did some work on post-reset chats recently, but the fixes probably aren't released yet.

**Comment by blainsmith** [comment]
I am seeing this as well on Arch Linux. I cannot remove it.

**Comment by maxtaco** [comment]
@blainsmith it looks like your folders are all rekeyed now, do you still see badging or notifications? can you put up a screenshot and a `keybase log send` if so?

**Comment by blainsmith** [comment]
@maxtaco Sure thing...

![screenshot_2017-12-06_08-49-30](https://user-images.githubusercontent.com/483829/33664693-85adc41e-da62-11e7-90ed-ad26fbe06cff.png)

```
------------
Success! Your log ID is:

  3ec24a22228a19f07fa5eb1c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%203ec24a22228a19f07fa5eb1c

Thanks!
------------
```

**Comment by maxtaco** [comment]
Thanks for sending.  Unrelated to the problems in this thread, that notification is because you reset your account, and we have some UI bugs for the small minority of people in this case. Cc @mmaxim who knows a fair amount about these.

**Comment by python273** [comment]
Entering paper key doesn't help ¯\\\_(ツ)_/¯
<img width="580" alt="screen shot 2017-12-14 at 6 10 33 pm" src="https://user-images.githubusercontent.com/3097956/33998938-1ea1c772-e0fa-11e7-968f-10b2f8bfc870.png">

**Comment by maxtaco** [comment]
We had a bug this morning, it should be fixed now, LMK if not?

**Comment by Poeticode** [comment]
So I've had this rekey issue for a while. I only use keybase to occasionally chat with friends, so I've been a terrible open-source user and ignored it. Last night, I tried to rekey with a paper key, and it said it was a success and would take a few minutes. But I couldn't press Okay, and the dialogue box remained indefinitely. 

I ran `keybase log send` about half an hour ago and it seems to be frozen, as well. I don't have anything on KBFS if this calls for a DB Nuke.

**Comment by maxtaco** [comment]
@Poeticode log send should take about 10 seconds. Can you try again?

**Comment by Poeticode** [comment]
Sure, @maxtaco ! I just ran the command again, and it's still getting stuck. The message looks odd, too.

```
$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs donât include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
canât read, for debugging purposes.
```

**Comment by maxtaco** [comment]
are you behind a proxy or firewall?

can you try

`keybase -d log send`
?

**Comment by Poeticode** [comment]
Ah, sorry about that. I was using Git Bash on Windows, which seemed to mess things up. I was successfully able to send a log using the regular command prompt. 

Log ID: cdddfd6bcb59365b2b25b41c

**Comment by maxtaco** [comment]
@strib seems like @Poeticode can't rekey his private folder...

**Comment by maxtaco** [comment]
ah, looks like KBFS is running....

**Comment by strib** [comment]
@Poeticode @maxtaco: The folder being complained about was reset in #6516, and isn't currently used.  So we just have to mark it broken on the server.  It should be fixed after the next server deploy.

**Comment by Poeticode** [comment]
Wow, I completely forgot that I had that issue. Thank you once again, @strib !

**Comment by ryanpcmcquen** [comment]
I am having the same issue. I think it is due to an ignored folder I no longer need ... how do I nuke it?

**Comment by jzila** [comment]
@ryanpcmcquen please `keybase log send` and respond here with a log ID. We will take a look.

**Comment by ryanpcmcquen** [comment]
@jzila, tracking at #14986.

**Comment by jzila** [comment]
Thanks!
